### PR TITLE
mention support for <video> tag as well

### PR DESCRIPTION
**Pull request by GorvGoyl**
This pull request closes (past link to GitHub issue here)

## Pre-Flight Checklist

I have made sure to:

- [ ] add tests & add a Storybook example (when this makes sense)
- [ ] manually test all the Storybook examples

### CODE REVIEW

**Comment by rpearce** [comment]
@GorvGoyl Thank you for opening this PR and wanting to add something to the docs! As it turns out, supporting things other than images is something that isn't sustainable for this project, and it won't be supported long-term.

Since it works in v4, I'll merge it, but I just thought you should know. Thanks for contributing!

**Review by rpearce — APPROVED** [review]

**Comment by GorvGoyl** [comment]
> @GorvGoyl Thank you for opening this PR and wanting to add something to the docs! As it turns out, supporting things other than images is something that isn't sustainable for this project, and it won't be supported long-term.
> 
> Since it works in v4, I'll merge it, but I just thought you should know. Thanks for contributing!

sure this makes sense. I tested it in v4 and it seems to be working fine (as of now).

**Comment by rpearce** [comment]
When I get time later, I'll add you to the all contributors section in the README

**Comment by rpearce** [comment]
Finally circled back to adding you to the contributors in the README. Thanks again!

**Pull request merged**
